### ISSUE TITLE
FMRS not working?

### ISSUE THREAD

**Issue by danieltatrai** [linuxgurugamer/FMRS#11]
Hi,

I tried to install it, after the old FMRS did not work anymore, but seems like it does not work (or am I messing something up?).

KSP Version: 1.8.1.2694

I copied the folder just before in GameData. No other mods I use.

Also it asks me after first launch whether I want FMRS for checking updates or not.

**Comment by linuxgurugamer** [comment]
you need the dependencies, ClickthroughBlocker & Toolbarcontroller

**Comment by danieltatrai** [comment]
OK, thank you for the response. I suspected, but it was not on the install instructions, to make sure I have those dependencies. Not even in changelogs mentioned, that these are NEEDED.

1.2.7
	Added support for the ToolbarController
	Added support for the ClickThrough Blocker
	Updated for 1.4.1+

It was not clear for me, maybe install instruction should contain it.

Anyway, thank you, I will check it.

**Comment by danieltatrai** [comment]
> OK, thank you for the response. I suspected, but it was not on the install instructions, to make sure I have those dependencies. Not even in changelogs mentioned, that these are NEEDED.
> 
> 1.2.7
> Added support for the ToolbarController
> Added support for the ClickThrough Blocker
> Updated for 1.4.1+
> 
> It was not clear for me, maybe install instruction should contain it.
> 
> Anyway, thank you, I will check it.

'Suprisingly' it worked out, thanks again!

**Comment by linuxgurugamer** [comment]
Great.
I'll get the instructions updated

**Comment by linuxgurugamer** [comment]
Just an FYI, if you look at the OP, you will see that the dependencies are listed there
