### ISSUE TITLE
Numerous parts errors

### ISSUE THREAD

**Issue by MrJadaml** [linuxgurugamer/FMRS#8]
Can't get FMRS to work. When looking in the ksp.log half of it is FMRS parts related errors.

ksp.log:
https://gist.github.com/MrJadaml/6f86327222122957d6951d794f38476c

Mac 10.12.6
Steam KSP 1.5.1.2335 (OSXPlayer)

let me know what I can do to help here.

**Comment by MrJadaml** [comment]
Was missing ClickthroughBlocker and ToolbarControl dependences: 
https://github.com/linuxgurugamer/KRASH/issues/29#issuecomment-439228527

**Comment by linuxgurugamer** [comment]
Please use the forums for support requests in the future.
Thank you
